name: Sync results from S3 to Git

on:
  workflow_call:
  workflow_dispatch:

env:
  S3_BUCKET: qstp-consul
  GIT_PAT_1: ${{ secrets.GH_ACCESS_TOKEN }}
  OUTPUT_DIR: ./allure-report
  SINGLE_FILE_DIR: ./allure-single-file
  SOURCE_DIR: ./allure-results

jobs:
  sync-results-s3-git:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Prepare Result Files
        run: |
          cd /tmp
          git clone https://github.com/Netcracker/qubership-testing-results
          echo "Clean git files"
          rm -rf /tmp/qubership-testing-results/Result/
          mkdir -p /tmp/qubership-testing-results/Result/
          aws s3 sync  "s3://qstp-consul/Result/" "/tmp/qubership-testing-results/Result/" --quiet

      - name: Push to Git
        run: |
          cd /tmp/qubership-testing-results
          git config --global user.email "NetcrackerCLPLCI@gmail.com"
          git config --global user.name "NetcrackerCLPLCI"
          git remote set-url origin https://${GIT_PAT_1}@github.com/Netcracker/qubership-testing-results.git
          [ -z "$(git status --porcelain)" ] && echo "âœ… No changes to commit and push" && exit 0
          echo "----->>>>"
          git add . -A >> /dev/null 
          git commit -a -m "Allure Results AutoSync" >> /dev/null 
          git push origin >> /dev/null